### ISSUE TITLE
Python library `warcio` complains about the formatting of the files

### ISSUE THREAD

**Issue by AngledLuffa** [JMMackenzie/CC-News-Tools#7]
This is maybe a minor issue, but the Python library `warcio` is complaining about the formatting of the files.

```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    for record in ArchiveIterator(stream):
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/warcio/archiveiterator.py", line 112, in _iterate_records
    self._raise_invalid_gzip_err()
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/warcio/archiveiterator.py", line 153, in _raise_invalid_gzip_err
    raise ArchiveLoadFailed(msg)
warcio.exceptions.ArchiveLoadFailed:
    ERROR: non-chunked gzip file detected, gzip block continues
    beyond single record.

    This file is probably not a multi-member gzip but a single gzip file.

    To allow seek, a gzipped WARC must have each record compressed into
    a single gzip member and concatenated together.

    This file is likely still valid and can be fixed by running:

    warcio recompress <path/to/file> <path/to/new_file>
```

Running the `recompress` option works fine, and my processing can continue from that point, but it's not a fast process.  Do you have any suggestions for how to work around this?  There's another python library out there, `warc`, but it's super old and does not work with python3.

Also, any thoughts on BeautifulSoup for python extraction of the text from the news articles?  Or is that something you haven't really considered?

**Comment by JMMackenzie** [comment]
It's probably because the new WARC files we produced are not really WARC compliant (we introduced additional header information for example). 

I never came across this problem (but was mostly using Apache Tika) -- I don't think other tooling (like Lucene) has the same problem, but I am not 100% sure. I think it should be viable to parse the data in a different way, but again, never tried it. 

Sorry, not very helpful!
